# -*- coding: utf-8 -*-
"""student performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmdqvDwtgrxQBUFhje-ShmjtuK0rL-Om
"""

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/StudentsPerformance.csv"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(file_path)
print("Dataset loaded successfully!")
print(df.head())

print("Shape of Dataset:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

categorical_features = df.select_dtypes(include='object').columns
print("Categorical Features:")
print(list(categorical_features))

for col in categorical_features:
    print("\n", col)
    print(df[col].value_counts())

df['Total Marks'] = (
    df['math score'] +
    df['reading score'] +
    df['writing score']
)

print(df[['math score', 'reading score', 'writing score', 'Total Marks']].head())

subject_columns = [
    'math score',
    'reading score',
    'writing score'
]

statistics = df[subject_columns].describe().T

print(statistics)

df['Percentage'] = (df['Total Marks'] / 300) * 100

print(df[['Total Marks', 'Percentage']].head())

for col in subject_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_limit) |
        (df[col] > upper_limit)
    ]

    print("\nSubject:", col)
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Lower Limit:", lower_limit)
    print("Upper Limit:", upper_limit)
    print("Number of Outliers:", len(outliers))

outlier_rows = pd.DataFrame()

for col in subject_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    temp = df[
        (df[col] < lower_limit) |
        (df[col] > upper_limit)
    ].copy()

    temp['Outlier Subject'] = col

    outlier_rows = pd.concat([outlier_rows, temp])

print(outlier_rows)

plt.figure(figsize=(10, 6))

sns.boxplot(data=df[subject_columns])

plt.title("Subject Score Outlier Detection")
plt.xlabel("Subjects")
plt.ylabel("Scores")

plt.show()

print(df.head())
print(df.shape)

print(df.isnull().sum())

df.to_csv("Student_Performance_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

print("STATISTICAL MEASURES")

for subject in subjects:
    print("\nSubject:", subject)
    print("Mean:", df[subject].mean())
    print("Median:", df[subject].median())
    print("Standard Deviation:", df[subject].std())
    print("Q1:", df[subject].quantile(0.25))
    print("Q2:", df[subject].quantile(0.50))
    print("Q3:", df[subject].quantile(0.75))

subject_means = df[subject_columns].mean()

print(subject_means)

subject_means.plot(kind='bar', figsize=(8,5))

plt.title("Average Score by Subject")
plt.xlabel("Subject")
plt.ylabel("Average Score")
plt.xticks(rotation=0)

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['Total Marks'], bins=20, kde=True)

plt.title("Distribution of Total Marks")
plt.xlabel("Total Marks")
plt.ylabel("Number of Students")

plt.show()

correlation = df[subject_columns].corr()

print(correlation)

plt.figure(figsize=(8,6))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title("Subject Score Correlation")

plt.show()

def performance_category(percentage):
    if percentage >= 75:
        return 'Excellent'
    elif percentage >= 60:
        return 'Good'
    elif percentage >= 40:
        return 'Average'
    else:
        return 'Poor'

df['Performance Category'] = df['Percentage'].apply(performance_category)

print(df[['Total Marks', 'Percentage', 'Performance Category']].head())

print(df['Performance Category'].value_counts())

print(df.head())
print("\nFinal Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())